services:
  es:
    image: elasticsearch:7.17.13
    networks:
      - backend-networks
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - trucks_db:/usr/share/elasticsearch/data
  
  backend:
    build: .
    restart: always
    networks:
      - backend-networks
      - frontend-networks
    depends_on:
      es:
        condition: service_healthy
  
  nginx:
    image: nginx:1.27.0-perl
    ports:
     - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./flask-app/static:/usr/share/nginx/html/static
      - ./flask-app/templates:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - frontend-networks


     
volumes:
  trucks_db:

networks:
  frontend-networks:
  backend-networks:
