services:
  backend:
    build: .
    restart: always
    networks:
      - truck-networks
    ports:
      - 5000:5000
    depends_on:
      es:
        condition: service_healthy
  
  es:
    image: elasticsearch:7.17.13
    networks:
      - truck-networks
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - trucks_db:/usr/share/elasticsearch/data
     
volumes:
  trucks_db:

networks:
  truck-networks:
